version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: "no"
    container_name: auth-mail-server
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth-mail
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - /Users/brook/mysql-container/auth-mail-server:/var/lib/mysql
